name: OutiServerPlugin
description: おうちサーバー用プラグイン
author: Ken_Cir
version: 3.2.0
api: 3.0.0
main: OutiServerPlugin\Main

commands:
  money:
    description: "所持金を確認する"
    usage: "/money <playername>"
    permission: OutiServerPlugin.command.*;OutiServerPlugin.command.money
  applewatch:
    description: "AppleWatchを出す"
    usage: "/applewatch"
    permission: OutiServerPlugin.command.*;OutiServerPlugin.command.applewatch
  reloadouticonfig:
    description: "configをリロード"
    usage: "/reloadouticonfig"
    permission: OutiServerPlugin.command.*
  reloadoutisound:
    description: "sound設定をリロード"
    usage: "/reloadoutisound"
    permission: OutiServerPlugin.command.*
  db:
    description: "dbを操作する"
    usage: "/db <query>"
    permission: OutiServerPlugin.command.*
  senddb:
    description: "dbファイルをDiscordに送信する"
    usage: "/senddb <query>"
    permission: OutiServerPlugin.command.*
  setitem:
    description: "アイテム設定"
    usage: "/setitem <itemid> <itemmeta> <日本語名> <画像パス>"
    permission: OutiServerPlugin.command.*

permissions:
  OutiServerPlugin.command.*:
    description: プレイヤーがOutiServerPluginのすべてのコマンドを使用できるようにします
    default: op
  OutiServerPlugin.command.money:
    description: プレイヤーがコマンドで所持金を確認できるようにします
    default: true
  OutiServerPlugin.command.applewatch:
    description: プレイヤーがコマンドでAppleWatchを使用できるようにします
    default: true