---
# ーーー DiscordBot関連の設定 ーーー
# DiscordBotのTOKEN
DiscordBot_Token: "DISCORD_TOKEN"

# DiscordギルドID
Discord_Guild_Id: "706452606918066237"

# Discordのチャット用チャンネルID
DiscordChat_Channel_Id: "834317763769925632"

# DiscordのLog用チャンネルID
DiscordLog_Channel_Id: "833626570270572584"

# Discordのdbを送信する用チャンネルID
DiscordDB_Channel_Id: "863124612429381699"

# DiscordのErrorLog用チャンネルID
DiscordErrorLog_Channel_id: "868787060394307604"

# DiscordのCommand Prefix
Discord_Command_Prefix: "?unko"

# ーーー土地関係の設定ーーー
# 土地購入を禁止するワールド
Land_Buy_Bans: []

# デフォルトの土地保護を解除するワールド(資源ワールドなど)
Land_Protection_Allow: []

# 1ブロックあたりの値段
Land_Price: 200

# ーーーAdminShop関係の設定ーーー
# デフォルトアイテムカテゴリー
Default_Item_Category: ["チート", "建材", "鉱石", "ツール", "防具", "エンチャント", "装飾", "食材", "醸造", "その他"]

# ーーー経済関係の設定ーーー
# 初期所持金
Default_Money: 1000

# ーーーカジノ関係の設定ーーー
# ーーースロットーーー

# スロット初期ジャックポット
Default_Slot_JP: 10000

# スロットでゾロ目が出た時の配当金
Default_Slot_Doublet: 1000

# Slot Mode1の一定額
NormalSlot_Mode1: 100000

# Slot Mode4の一定回数
NormalSlot_Mode4: 1000

# Slot Mode5の確率 ○分の1
NormalSlot_Mode5: 1000

# カイジスロット Mode0の3段階目高確率にするか
KaijiSlot_Mode0: false

# カイジ大当たり
KaijiSlot_JP: 2000000
...
